Repository Trys-Ketch/trys-ketch-server, pull requests merged in 2023-01, with the labels that each got.

#3 [FEAT] OAuth2.0 카카오톡 로그인 구현
  src/main/java/com/project/trysketch/global/dto/MsgResponseDto.java
  src/main/java/com/project/trysketch/global/dto/ResponseMsgDto.java
  src/main/java/com/project/trysketch/global/jwt/JwtAuthFilter.java
  src/main/java/com/project/trysketch/global/jwt/JwtUtil.java
  src/main/java/com/project/trysketch/user/controller/UserController.java
  src/main/java/com/project/trysketch/user/dto/KakaoUserRequstDto.java
  src/main/java/com/project/trysketch/user/entity/User.java
  src/main/java/com/project/trysketch/user/repository/UserRepository.java
  src/main/java/com/project/trysketch/user/service/KakaoService.java
  src/main/java/com/project/trysketch/user/service/UserService.java
Labels: ✨feature

#4 [FIX] 재로그인 관련한 예외처리, OAuth2.0 로그인시 토큰 반환 방식 지정 (#2)
  src/main/java/com/project/trysketch/global/jwt/JwtAuthFilter.java
  src/main/java/com/project/trysketch/global/jwt/JwtUtil.java
  src/main/java/com/project/trysketch/global/security/UserDetailsServiceImpl.java
  src/main/java/com/project/trysketch/user/controller/UserController.java
  src/main/java/com/project/trysketch/user/service/KakaoService.java
Labels: 🔨fix

#9 [REFACTOR] S3업로드 다수의 이미지에서 한 개의 이미지로 바꿈, 주석추가
  build.gradle
  src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
  src/main/java/com/project/trysketch/image/AmazonS3Service.java
  src/main/java/com/project/trysketch/image/ImageFile.java
  src/main/java/com/project/trysketch/image/ImageFileRepository.java
  src/main/java/com/project/trysketch/image/ImageLikeController.java
  src/main/java/com/project/trysketch/image/ImageLikeRequestDto.java
  src/main/java/com/project/trysketch/image/ImageLikeService.java
  src/main/java/com/project/trysketch/user/controller/UserController.java
  src/main/resources/application-key.properties
  src/main/resources/application.properties
Labels: ♻refactor

#13 [FEAT] Redis 기능 추가
  build.gradle
  src/main/java/com/project/trysketch/TrysKetchApplication.java
  src/main/java/com/project/trysketch/global/config/WebSecurityConfig.java
  src/main/java/com/project/trysketch/global/jwt/JwtUtil.java
  src/main/java/com/project/trysketch/redis/config/RedisConfig.java
  src/main/java/com/project/trysketch/redis/dto/NonMember.java
  src/main/java/com/project/trysketch/redis/dto/NonMemberNickRequestDto.java
  src/main/java/com/project/trysketch/redis/repositorty/RedisAccessTokenRepository.java
  src/main/java/com/project/trysketch/redis/service/RedisService.java
  src/main/java/com/project/trysketch/suggest/AdjectiveEntity.java
  src/main/java/com/project/trysketch/suggest/AdjectiveRepository.java
  src/main/java/com/project/trysketch/suggest/NounEntity.java
  src/main/java/com/project/trysketch/suggest/NounRepository.java
  src/main/java/com/project/trysketch/user/controller/UserController.java
  src/main/java/com/project/trysketch/user/entity/RandomNick.java
  src/main/java/com/project/trysketch/user/repository/RandomNickRepository.java
  src/main/java/com/project/trysketch/user/service/KakaoService.java
  src/main/java/com/project/trysketch/user/service/UserService.java
Labels: ✨feature

#15 [FEAT] OAuth2.0 카카오톡 로그인 시 랜덤 닉네임 부여
  src/main/java/com/project/trysketch/user/repository/RandomNickRepository.java
  src/main/java/com/project/trysketch/user/service/KakaoService.java
  src/main/java/com/project/trysketch/user/service/UserService.java
Labels: ✨feature

#17 [FEAT] WebRTC, WebSocket 관련 Signaling Server 구축
  build.gradle
  src/main/java/com/project/trysketch/global/config/WebRtcConfig.java
  src/main/java/com/project/trysketch/global/config/WebSocketConfig.java
  src/main/java/com/project/trysketch/global/rtc/ChatMessage.java
  src/main/java/com/project/trysketch/global/rtc/Room.java
  src/main/java/com/project/trysketch/global/rtc/SignalingHandler.java
  src/main/java/com/project/trysketch/global/rtc/WebSocketMessage.java
Labels: ✨feature

#24 Feature/20
  src/main/java/com/project/trysketch/gameroom/service/GameRoomService.java
  src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
  src/main/java/com/project/trysketch/global/jwt/JwtUtil.java
Labels: 🔨fix

#25 [FEAT] S3 관련 - 그림 좋아요 취소기능 추가 및 httpservlet로 변경 (#23)
  src/main/java/com/project/trysketch/gameroom/service/GameRoomService.java
  src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
  src/main/java/com/project/trysketch/global/jwt/JwtUtil.java
  src/main/java/com/project/trysketch/image/ImageController.java
  src/main/java/com/project/trysketch/image/ImageLikeRepository.java
  src/main/java/com/project/trysketch/image/ImageService.java
Labels: ✨feature

#28 [FEAT] 게임 메인 로직 구현 (#26)
  src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
  src/main/java/com/project/trysketch/maingame/controller/GameController.java
  src/main/java/com/project/trysketch/maingame/entity/GameInfo.java
  src/main/java/com/project/trysketch/maingame/service/GameService.java
Labels: ✨feature

#30 [FEAT] Scheduler 이용해서 좋아요 안눌린 S3의 그림 주기적으로 삭제하는 기능 (#29)
  build.gradle
  src/main/java/com/project/trysketch/TrysKetchApplication.java
  src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
  src/main/java/com/project/trysketch/image/AmazonS3Service.java
  src/main/java/com/project/trysketch/image/Image.java
  src/main/java/com/project/trysketch/image/ImageController.java
  src/main/java/com/project/trysketch/image/ImageLike.java
  src/main/java/com/project/trysketch/image/ImageLikeRepository.java
  src/main/java/com/project/trysketch/image/ImageRepository.java
  src/main/java/com/project/trysketch/image/ImageService.java
  src/main/java/com/project/trysketch/image/Scheduler.java
Labels: ✨feature

#33 리소스 낭비하지 않도록 scheduler 주기 2분 -> 5시간으로 변경 (#29)
  src/main/java/com/project/trysketch/image/Scheduler.java
Labels: ♻refactor

#35 [CHORE] 기능 추가 및 연관된 로직 병합 (#5)
  src/main/java/com/project/trysketch/controller/GameRoomController.java
  src/main/java/com/project/trysketch/dto/response/GameRoomResponseDto.java
  src/main/java/com/project/trysketch/entity/GameRoomUser.java
  src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
  src/main/java/com/project/trysketch/global/jwt/JwtAuthFilter.java
  src/main/java/com/project/trysketch/redis/dto/GuestEnum.java
  src/main/java/com/project/trysketch/redis/dto/StaticString.java
  src/main/java/com/project/trysketch/redis/service/RedisService.java
  src/main/java/com/project/trysketch/repository/GameRoomUserRepository.java
  src/main/java/com/project/trysketch/service/GameRoomService.java
  src/main/java/com/project/trysketch/service/UserService.java
Labels: 🔨fix

#37 [REFATOR] WebRTC 다대다 연결 구현
  src/main/java/com/project/trysketch/global/config/WebRtcConfig.java
  src/main/java/com/project/trysketch/global/rtc/ChatMessage.java
  src/main/java/com/project/trysketch/global/rtc/Message.java
  src/main/java/com/project/trysketch/global/rtc/Room.java
  src/main/java/com/project/trysketch/global/rtc/SignalingHandler.java
  src/main/java/com/project/trysketch/global/rtc/Utils.java
  src/main/java/com/project/trysketch/global/rtc/WebSocketMessage.java
Labels: ♻refactor

#40 [FIX] 기능 추가 및 연관된 로직 병합 (#5)
  src/main/java/com/project/trysketch/global/config/WebSecurityConfig.java
  src/main/java/com/project/trysketch/repository/GameRoomUserRepository.java
  src/main/java/com/project/trysketch/service/GameRoomService.java
Labels: 🔨fix

#42 [FEAT] WebRTC에 게임방 로직 연결
  src/main/java/com/project/trysketch/global/jwt/JwtUtil.java
  src/main/java/com/project/trysketch/global/rtc/Message.java
  src/main/java/com/project/trysketch/global/rtc/SignalingHandler.java
  src/main/java/com/project/trysketch/repository/GameRoomUserRepository.java
  src/main/java/com/project/trysketch/service/GameRoomService.java
Labels: ✨feature

#44 [FEAT] 총 페이지수 가져오기
  src/main/java/com/project/trysketch/dto/response/GameRoomResponseDto.java
  src/main/java/com/project/trysketch/service/GameRoomService.java
Labels: ✨feature

#45 [FIX] 변수명 변경, WebRTC 관련 CORS 설정
  src/main/java/com/project/trysketch/entity/GameRoomUser.java
  src/main/java/com/project/trysketch/global/config/WebRtcConfig.java
  src/main/java/com/project/trysketch/global/config/WebSecurityConfig.java
  src/main/java/com/project/trysketch/repository/GameRoomUserRepository.java
  src/main/java/com/project/trysketch/service/GameRoomService.java
Labels: 🐞bug

#48 [FEAT] getAllGameRoom 반환정보 수정 (#47)
  src/main/java/com/project/trysketch/service/GameRoomService.java
Labels: ✨feature

#49 [FIX] 기능 추가 및 연관된 로직 병합 (#5)
  src/main/java/com/project/trysketch/controller/GameRoomController.java
  src/main/java/com/project/trysketch/dto/response/GameRoomResponseDto.java
  src/main/java/com/project/trysketch/entity/GameRoom.java
  src/main/java/com/project/trysketch/global/jwt/JwtUtil.java
  src/main/java/com/project/trysketch/global/rtc/SignalingHandler.java
  src/main/java/com/project/trysketch/redis/dto/GamerKey.java
  src/main/java/com/project/trysketch/redis/service/RedisService.java
  src/main/java/com/project/trysketch/repository/GameRoomUserRepository.java
  src/main/java/com/project/trysketch/service/GameRoomService.java
  src/main/java/com/project/trysketch/service/GameService.java
Labels: 🔨fix

#50 [FEAT] 게임 시작 로직 구현 (#26)
  src/main/java/com/project/trysketch/controller/GameController.java
  src/main/java/com/project/trysketch/controller/GameRoomController.java
  src/main/java/com/project/trysketch/dto/response/GameStartResponseDto.java
  src/main/java/com/project/trysketch/entity/GameInfo.java
  src/main/java/com/project/trysketch/global/dto/DataMsgResponseDto.java
  src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
  src/main/java/com/project/trysketch/repository/GameInfoRepository.java
  src/main/java/com/project/trysketch/service/GameService.java
Labels: ✨feature

#51 [REFACTOR] 기능 추가 및 연관된 로직 병합 (#5)
  src/main/java/com/project/trysketch/controller/GameRoomController.java
  src/main/java/com/project/trysketch/dto/response/GameRoomResponseDto.java
  src/main/java/com/project/trysketch/entity/GameInfo.java
  src/main/java/com/project/trysketch/redis/service/RedisService.java
  src/main/java/com/project/trysketch/service/GameRoomService.java
Labels: ♻refactor

#53 [FEAT] 게임 메인 로직 구현 (#26)
  src/main/java/com/project/trysketch/controller/GameController.java
  src/main/java/com/project/trysketch/dto/response/GameStartResponseDto.java
  src/main/java/com/project/trysketch/entity/GameFlow.java
  src/main/java/com/project/trysketch/entity/GameInfo.java
  src/main/java/com/project/trysketch/service/GameService.java
Labels: ✨feature

#55 [FEAT] 게임 메인 로직 구현 (#26)
  src/main/java/com/project/trysketch/controller/GameController.java
  src/main/java/com/project/trysketch/entity/GameFlow.java
  src/main/java/com/project/trysketch/entity/GameInfo.java
  src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
  src/main/java/com/project/trysketch/repository/GameFlowRepository.java
  src/main/java/com/project/trysketch/repository/GameInfoRepository.java
  src/main/java/com/project/trysketch/service/GameService.java
Labels: ✨feature

#56 [FEAT] 게임 결과 보여주는 로직 구현 (#26)
  src/main/java/com/project/trysketch/controller/GameController.java
  src/main/java/com/project/trysketch/controller/GameRoomController.java
  src/main/java/com/project/trysketch/dto/response/GameRoomResponseDto.java
  src/main/java/com/project/trysketch/dto/response/ImageResponseDto.java
  src/main/java/com/project/trysketch/dto/response/KeywordResponseDto.java
  src/main/java/com/project/trysketch/entity/GameFlow.java
  src/main/java/com/project/trysketch/entity/GameRoom.java
  src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
  src/main/java/com/project/trysketch/image/AmazonS3Service.java
  src/main/java/com/project/trysketch/image/ImageController.java
  src/main/java/com/project/trysketch/image/ImageService.java
  src/main/java/com/project/trysketch/image/Scheduler.java
  src/main/java/com/project/trysketch/repository/GameFlowRepository.java
  src/main/java/com/project/trysketch/service/GameRoomService.java
  src/main/java/com/project/trysketch/service/GameService.java
Labels: ✨feature

#57 [FEAT] 게임 준비, 게임 시작 로직 구현
  src/main/java/com/project/trysketch/entity/GameRoomUser.java
  src/main/java/com/project/trysketch/global/rtc/Message.java
  src/main/java/com/project/trysketch/global/rtc/SignalingHandler.java
  src/main/java/com/project/trysketch/repository/GameRoomUserRepository.java
  src/main/java/com/project/trysketch/service/GameRoomService.java
  src/main/java/com/project/trysketch/service/GameService.java
Labels: ✨feature

#59 [REFACTOR] GameRoom Entity에 status -> isPlaying으로 변경
  src/main/java/com/project/trysketch/entity/GameRoom.java
  src/main/java/com/project/trysketch/global/rtc/SignalingHandler.java
  src/main/java/com/project/trysketch/service/GameRoomService.java
  src/main/java/com/project/trysketch/service/GameService.java
Labels: ♻refactor

#63 [FEAT] 회원 & 비회원 정보 조회 API 구현
  src/main/java/com/project/trysketch/controller/UserController.java
  src/main/java/com/project/trysketch/entity/GameRoomUser.java
  src/main/java/com/project/trysketch/entity/ThumbImg.java
  src/main/java/com/project/trysketch/entity/User.java
  src/main/java/com/project/trysketch/redis/dto/GamerKey.java
  src/main/java/com/project/trysketch/redis/dto/GuestNickRequestDto.java
  src/main/java/com/project/trysketch/redis/entity/Guest.java
  src/main/java/com/project/trysketch/redis/service/RedisService.java
  src/main/java/com/project/trysketch/repository/ThumbImgRepository.java
  src/main/java/com/project/trysketch/service/KakaoService.java
  src/main/java/com/project/trysketch/service/UserService.java
Labels: ✨feature

#65 [REFACTOR] 를 이용한 웹소켓 채팅 구현 (#62)
  src/main/java/com/project/trysketch/controller/UserController.java
  src/main/java/com/project/trysketch/entity/GameRoomUser.java
  src/main/java/com/project/trysketch/redis/config/RedisConfig.java
  src/main/java/com/project/trysketch/redis/dto/GamerEnum.java
  src/main/java/com/project/trysketch/redis/entity/CacheKey.java
  src/main/java/com/project/trysketch/redis/service/RedisService.java
  src/main/java/com/project/trysketch/repository/ThumbImgRepository.java
  src/main/java/com/project/trysketch/service/GameRoomService.java
  src/main/java/com/project/trysketch/service/GameService.java
  src/main/java/com/project/trysketch/service/UserService.java
Labels: 🔨fix

#67 [FEAT] 게임 메인 로직에 WebSocket STOMP 적용
  build.gradle
  src/main/java/com/project/trysketch/controller/ChatController.java
  src/main/java/com/project/trysketch/controller/GameController.java
  src/main/java/com/project/trysketch/dto/request/GameFlowRequestDto.java
  src/main/java/com/project/trysketch/dto/response/GameRoomResponseDto.java
  src/main/java/com/project/trysketch/entity/GameRoomUser.java
  src/main/java/com/project/trysketch/global/config/SwaggerConfig.java
  src/main/java/com/project/trysketch/global/config/WebSocketConfig.java
  src/main/java/com/project/trysketch/global/rtc/SignalingHandler.java
  src/main/java/com/project/trysketch/service/GameRoomService.java
  src/main/java/com/project/trysketch/service/GameService.java
  src/main/java/com/project/trysketch/service/UserService.java
Labels: ✨feature, 🔨fix

#69 레디스 캐시 적용 및 코드 일부 수정
  src/main/java/com/project/trysketch/TrysKetchApplication.java
  src/main/java/com/project/trysketch/controller/UserController.java
  src/main/java/com/project/trysketch/redis/config/RedisConfig.java
  src/main/java/com/project/trysketch/redis/dto/TestDto.java
  src/main/java/com/project/trysketch/redis/entity/CacheKey.java
  src/main/java/com/project/trysketch/redis/entity/Guest.java
  src/main/java/com/project/trysketch/redis/repositorty/GuestRepository.java
  src/main/java/com/project/trysketch/redis/service/RedisService.java
  src/main/java/com/project/trysketch/repository/GameFlowRepository.java
  src/main/java/com/project/trysketch/service/UserService.java
Labels: ✨feature, 🔨fix

#71 [FEAT] 초대코드 발급 기능 추가 (#70)
  src/main/java/com/project/trysketch/controller/GameRoomController.java
  src/main/java/com/project/trysketch/entity/GameRoom.java
  src/main/java/com/project/trysketch/repository/GameRoomRepository.java
  src/main/java/com/project/trysketch/service/GameRoomService.java
Labels: ✨feature

#72 [FEAT] 게임 강제종료 api 구현
  src/main/java/com/project/trysketch/controller/GameController.java
  src/main/java/com/project/trysketch/service/GameService.java
Labels: ✨feature

#74 [FEAT] 닉네임, 방제목 정규식 적용 (#73)
  src/main/java/com/project/trysketch/controller/GameRoomController.java
  src/main/java/com/project/trysketch/dto/request/GameRoomRequestDto.java
  src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
  src/main/java/com/project/trysketch/redis/dto/GuestNickRequestDto.java
Labels: ✨feature

#77 [FIX] 캐시 적용 하기 (#64)
  src/main/java/com/project/trysketch/redis/config/RedisConfig.java
Labels: 🐞bug

#78 [REFACTOR] 게임방 입장, 조회 시 response 변경 (#70)
  src/main/java/com/project/trysketch/controller/GameRoomController.java
  src/main/java/com/project/trysketch/dto/response/GameRoomResponseDto.java
  src/main/java/com/project/trysketch/global/dto/DataMsgResponseDto.java
  src/main/java/com/project/trysketch/service/GameRoomService.java
Labels: ✨feature

#79 [FEAT] SSE 이용한 실시간 게임방조회 로직 코드 (#68)
  src/main/java/com/project/trysketch/global/dto/DataMsgResponseDto.java
  src/main/java/com/project/trysketch/repository/GameRoomRepository.java
  src/main/java/com/project/trysketch/service/GameRoomService.java
  src/main/java/com/project/trysketch/sse/SseController.java
  src/main/java/com/project/trysketch/sse/SseEmitters.java
Labels: ✨feature

#80 [REFACTOR] SSE를 이용한 실시간 게임방 조회 (#68)
  src/main/java/com/project/trysketch/global/dto/DataMsgResponseDto.java
  src/main/java/com/project/trysketch/service/GameRoomService.java
Labels: 🔨fix

#81 [FEAT] 게임 메인 로직 WebSocket STOMP 적용
  src/main/java/com/project/trysketch/controller/GameController.java
  src/main/java/com/project/trysketch/controller/GameRoomController.java
  src/main/java/com/project/trysketch/dto/request/GameFlowRequestDto.java
  src/main/java/com/project/trysketch/entity/GameFlow.java
  src/main/java/com/project/trysketch/entity/GameRoomUser.java
  src/main/java/com/project/trysketch/global/config/WebSecurityConfig.java
  src/main/java/com/project/trysketch/global/config/WebSocketConfig.java
  src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
  src/main/java/com/project/trysketch/global/rtc/SignalingHandler.java
  src/main/java/com/project/trysketch/image/AmazonS3Service.java
  src/main/java/com/project/trysketch/repository/GameFlowRepository.java
  src/main/java/com/project/trysketch/service/GameRoomService.java
  src/main/java/com/project/trysketch/service/GameService.java
Labels: ✨feature, 🔨fix, ♻refactor

#83 [REFACTOR] 비회원 랜덤 프로필 이미지 순서, 게임 방 나가기 API uri 수정 (#62)
  src/main/java/com/project/trysketch/controller/GameRoomController.java
  src/main/java/com/project/trysketch/service/UserService.java
Labels: ♻refactor

#85 [REFACTOR] 정규식 수정 (#73)
  src/main/java/com/project/trysketch/dto/request/GameRoomRequestDto.java
Labels: ✨feature

#90 [FIX] 게임 중 예외처리 (#87)
  src/main/java/com/project/trysketch/entity/GameRoom.java
  src/main/java/com/project/trysketch/service/GameRoomService.java
Labels: 🔨fix

#94 [REFACTOR] Websocket으로 게임 준비방까지 연결
  src/main/java/com/project/trysketch/global/config/WebSecurityConfig.java
  src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
  src/main/java/com/project/trysketch/global/rtc/Message.java
  src/main/java/com/project/trysketch/global/rtc/SignalingHandler.java
  src/main/java/com/project/trysketch/repository/GameRoomUserRepository.java
  src/main/java/com/project/trysketch/service/GameRoomService.java
  src/main/java/com/project/trysketch/service/GameService.java
  src/main/java/com/project/trysketch/service/UserService.java
Labels: ♻refactor

#97 [FIX] 로그인 관련 오류 해결 (#96)
  src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
  src/main/java/com/project/trysketch/service/KakaoService.java
  src/main/java/com/project/trysketch/service/UserService.java
Labels: 🔨fix

#98 [FIX] 닉네임 유효성 적용되도록 수정 (#96)
  src/main/java/com/project/trysketch/controller/UserController.java
Labels: 🔨fix

#99 [REFACTOR] 방 디테일 조회 API 추가 (#95)
  src/main/java/com/project/trysketch/controller/GameRoomController.java
  src/main/java/com/project/trysketch/repository/GameRoomUserRepository.java
  src/main/java/com/project/trysketch/service/GameRoomService.java
Labels: 🔨fix, ♻refactor

#101 [REFACTOR] 닉네임 유효성 변경 (띄어쓰기 추가) (#73)
  src/main/java/com/project/trysketch/redis/dto/GuestNickRequestDto.java
Labels: 🔨fix

#102 [REFACTOR] 필요한 매개변수만 받아오는 코드로 변경 (#100)
  src/main/java/com/project/trysketch/controller/GameRoomController.java
  src/main/java/com/project/trysketch/global/rtc/SignalingHandler.java
  src/main/java/com/project/trysketch/repository/GameRoomUserRepository.java
  src/main/java/com/project/trysketch/service/GameRoomService.java
Labels: ♻refactor

#103 [REFACTOR] 웹소켓, STOMP 적용한 채팅기능 구현 (#76)
  src/main/java/com/project/trysketch/chatting/ChatController.java
  src/main/java/com/project/trysketch/chatting/ChatPublisher.java
  src/main/java/com/project/trysketch/chatting/ChatRoom.java
  src/main/java/com/project/trysketch/chatting/ChatRoomRepository.java
  src/main/java/com/project/trysketch/chatting/ChatSubscriber.java
  src/main/java/com/project/trysketch/redis/config/RedisConfig.java
  src/main/java/com/project/trysketch/service/GameRoomService.java
Labels: ♻refactor

#107 [FEAT] 마이페이지 기능 구현
  src/main/java/com/project/trysketch/dto/response/UserResponseDto.java
  src/main/java/com/project/trysketch/entity/User.java
  src/main/java/com/project/trysketch/image/ImageController.java
  src/main/java/com/project/trysketch/image/ImageService.java
Labels: ✨feature

#108 [FIX] 재게임시 방장 여부 미전달 버그 (#104)
  src/main/java/com/project/trysketch/global/rtc/SignalingHandler.java
Labels: 🔨fix

#113 [FEAT] 네이버 소셜로그인기능구현 (#112)
  src/main/java/com/project/trysketch/controller/UserController.java
  src/main/java/com/project/trysketch/dto/response/NaverResponseDto.java
  src/main/java/com/project/trysketch/entity/User.java
  src/main/java/com/project/trysketch/repository/UserRepository.java
  src/main/java/com/project/trysketch/service/NaverService.java
Labels: ✨feature

#114 [REFACTOR] 네이버, 구글과 코드 통일 위한 redirect URI 주소 변경 (#2)
  src/main/java/com/project/trysketch/service/KakaoService.java
Labels: ♻refactor

#115 [FIX] 중복 제출 해결, GameService 리팩토링
  src/main/java/com/project/trysketch/controller/GameController.java
  src/main/java/com/project/trysketch/dto/request/GameFlowRequestDto.java
  src/main/java/com/project/trysketch/entity/GameFlow.java
  src/main/java/com/project/trysketch/repository/GameFlowRepository.java
  src/main/java/com/project/trysketch/service/AmazonS3Service.java
  src/main/java/com/project/trysketch/service/GameService.java
Labels: 🔨fix, ♻refactor

#116 [FIX] NaverService 버그 수정
  src/main/java/com/project/trysketch/dto/request/NaverRequestDto.java
  src/main/java/com/project/trysketch/service/NaverService.java
Labels: 🔨fix

#118 [FEAT] 구글 Oauth2 구현 및 버그 수정 (#111)
  build.gradle
  src/main/java/com/project/trysketch/controller/UserController.java
  src/main/java/com/project/trysketch/dto/request/OAuthRequestDto.java
  src/main/java/com/project/trysketch/entity/User.java
  src/main/java/com/project/trysketch/repository/UserRepository.java
  src/main/java/com/project/trysketch/service/GoogleService.java
  src/main/java/com/project/trysketch/service/KakaoService.java
  src/main/java/com/project/trysketch/service/NaverService.java
Labels: ✨feature, 🔨fix

#119 [FIX] 재게임시 방장 여부 미전달 버그 (#104)
  src/main/java/com/project/trysketch/global/rtc/SignalingHandler.java
  src/main/java/com/project/trysketch/service/GameService.java
Labels: 🔨fix

#121 유저 활동내역 저장기능 구현, 업적 기능 구현
  src/main/java/com/project/trysketch/controller/UserController.java
  src/main/java/com/project/trysketch/entity/Achievement.java
  src/main/java/com/project/trysketch/entity/History.java
  src/main/java/com/project/trysketch/entity/User.java
  src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
  src/main/java/com/project/trysketch/global/utill/AchievementCode.java
  src/main/java/com/project/trysketch/repository/AchievementRepository.java
  src/main/java/com/project/trysketch/repository/HistoryRepository.java
  src/main/java/com/project/trysketch/service/GoogleService.java
  src/main/java/com/project/trysketch/service/HistoryService.java
Labels: ✨feature

#123 [FIX] 게임 중 퇴장하더라도 정상 진행되도록 구현 (#122)
  src/main/java/com/project/trysketch/dto/response/GameRoomResponseDto.java
  src/main/java/com/project/trysketch/entity/GameRoom.java
  src/main/java/com/project/trysketch/entity/UnsubmissionImg.java
  src/main/java/com/project/trysketch/global/rtc/SignalingHandler.java
  src/main/java/com/project/trysketch/repository/GameFlowRepository.java
  src/main/java/com/project/trysketch/repository/UnsubmissionImgRepository.java
  src/main/java/com/project/trysketch/service/GameService.java
Labels: 🔨fix

#124 [FIX] History, Achievement 관련 기능 구현 (#117)
  src/main/java/com/project/trysketch/controller/UserController.java
  src/main/java/com/project/trysketch/entity/History.java
  src/main/java/com/project/trysketch/entity/User.java
  src/main/java/com/project/trysketch/service/GoogleService.java
  src/main/java/com/project/trysketch/service/HistoryService.java
Labels: 🔨fix

#127 유저 활동내역 저장기능 구현, 업적 기능 구현
  src/main/java/com/project/trysketch/entity/History.java
  src/main/java/com/project/trysketch/service/HistoryService.java
  src/main/java/com/project/trysketch/service/KakaoService.java
  src/main/java/com/project/trysketch/service/NaverService.java
Labels: ✨feature

#128 [FEAT] 결과창 방장이 원하는 순서대로 보여주기 (#126)
  src/main/java/com/project/trysketch/controller/GameController.java
  src/main/java/com/project/trysketch/entity/GameRoom.java
  src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
  src/main/java/com/project/trysketch/service/GameService.java
Labels: ✨feature

#130 [DOCS] 에러 메시지 마침표 제거 (#129)
  src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
Labels: 📝documentation

#132 [REFACTOR] 레디스 관련 만료시간 수정 (#5)
  src/main/java/com/project/trysketch/dto/CacheKey.java
  src/main/java/com/project/trysketch/entity/Guest.java
  src/main/java/com/project/trysketch/repository/GuestRepository.java
  src/main/java/com/project/trysketch/service/UserService.java
Labels: ♻refactor

#134 유저 활동내역 저장기능 구현, 업적 기능 구현
  src/main/java/com/project/trysketch/service/GoogleService.java
  src/main/java/com/project/trysketch/service/HistoryService.java
  src/main/java/com/project/trysketch/service/KakaoService.java
  src/main/java/com/project/trysketch/service/NaverService.java
Labels: 🔨fix

#136 [REFACTOR] SignalingHandler 리팩토링 (#131)
  src/main/java/com/project/trysketch/global/rtc/Message.java
  src/main/java/com/project/trysketch/global/rtc/SignalingHandler.java
  src/main/java/com/project/trysketch/service/GameRoomService.java
Labels: ♻refactor

#138 [FEAT] 게임중 제출인원 표시 (#133)
  src/main/java/com/project/trysketch/controller/GameController.java
  src/main/java/com/project/trysketch/repository/GameRoomUserRepository.java
  src/main/java/com/project/trysketch/service/GameService.java
Labels: ✨feature

#139 [FEAT] 게임 진행 인원 4명 미만될 시 강제종료 구현 (#137)
  src/main/java/com/project/trysketch/global/rtc/SignalingHandler.java
  src/main/java/com/project/trysketch/service/GameRoomService.java
  src/main/java/com/project/trysketch/service/GameService.java
Labels: ✨feature

#140 [REFACTOR] 게임중 제출인원 코드 리팩토링 (#126)
  src/main/java/com/project/trysketch/controller/GameController.java
  src/main/java/com/project/trysketch/service/GameService.java
Labels: ♻refactor

#141 [REFACTOR] 방장이 강퇴시 DB 에서 바로 제거 (#120)
  src/main/java/com/project/trysketch/global/rtc/SignalingHandler.java
  src/main/java/com/project/trysketch/service/GameRoomService.java
  src/main/java/com/project/trysketch/service/GameService.java
Labels: ♻refactor

#143 [FEAT] 결과 페이지에 프로필사진 및 게임유저 리스트 추가 (#142)
  src/main/java/com/project/trysketch/entity/GameFlow.java
  src/main/java/com/project/trysketch/entity/GameRoomUser.java
  src/main/java/com/project/trysketch/service/GameService.java
Labels: ✨feature

#144 [REFACTOR] 비회원 토큰 만료시간 10시간으로 복귀 (#5)
  src/main/java/com/project/trysketch/dto/CacheKey.java
  src/main/java/com/project/trysketch/entity/Guest.java
Labels: ♻refactor

#147 [FIX] 소셜(naver, kakao, google) 로그인시 history NullPointerException 에러 해결
  src/main/java/com/project/trysketch/entity/History.java
  src/main/java/com/project/trysketch/entity/User.java
  src/main/java/com/project/trysketch/service/KakaoService.java
  src/main/java/com/project/trysketch/service/NaverService.java
Labels: 🐞bug

#148 [FIX] 일괄 자동 제출 후 발생하던 DB 동시 접근 이슈, Synchronized 적용하여 동시성 제어 (#145)
  src/main/java/com/project/trysketch/controller/GameController.java
  src/main/java/com/project/trysketch/service/GameService.java
Labels: 🔨fix

#150 [FIX] 게임 중 유저 나갈 시 게임 종료되어도 gameFlow 안 지워지는 에러해결 (#149)
  src/main/java/com/project/trysketch/entity/GameFlow.java
  src/main/java/com/project/trysketch/entity/GameRoomUser.java
  src/main/java/com/project/trysketch/service/GameRoomService.java
  src/main/java/com/project/trysketch/service/GameService.java
Labels: 🐞bug

#152 [FIX] 오류 발생한 gameRoom 나와서 다른방 입장 시도시 입장 안 되는 에러 해결 (151)
  src/main/java/com/project/trysketch/repository/GameRoomUserRepository.java
  src/main/java/com/project/trysketch/service/GameRoomService.java
  src/main/java/com/project/trysketch/service/GameService.java
Labels: 🐞bug

#154 [REFACTOR] 이미지 관련 파일 수정,추가 (#153)
  src/main/java/com/project/trysketch/controller/ImageController.java
  src/main/java/com/project/trysketch/dto/response/ImageLikeResponseDto.java
  src/main/java/com/project/trysketch/entity/GameFlow.java
  src/main/java/com/project/trysketch/entity/Image.java
  src/main/java/com/project/trysketch/repository/ImageLikeRepository.java
  src/main/java/com/project/trysketch/service/AmazonS3Service.java
  src/main/java/com/project/trysketch/service/GameService.java
  src/main/java/com/project/trysketch/service/ImageService.java
Labels: ♻refactor

#158 [FIX] 중도 이탈 유저 발생 시 에러 (#157)
  src/main/java/com/project/trysketch/service/GameService.java
Labels: 🐞bug, 🔨fix

#156 [REFACTOR] 이미지 좋아요 관련 기능 수정 (#155)
  src/main/java/com/project/trysketch/controller/ImageController.java
  src/main/java/com/project/trysketch/service/ImageService.java
Labels: ♻refactor

#161 [FIX] WebSocket STOMP 버퍼 사이즈 증축 (#160)
  src/main/java/com/project/trysketch/global/config/WebSocketConfig.java
  src/main/java/com/project/trysketch/global/stomp/AgentWebSocketHandlerDecoratorFactory.java
  src/main/java/com/project/trysketch/global/stomp/SubProtocolWebSocketHandlerInterceptor.java
Labels: 🐞bug, 🔨fix

#162 [FIX] WebSocket STOMP 버퍼 사이즈 증축 변경 (#160)
  src/main/java/com/project/trysketch/global/config/WebSocketConfig.java
  src/main/java/com/project/trysketch/global/stomp/AgentWebSocketHandlerDecoratorFactory.java
  src/main/java/com/project/trysketch/global/stomp/SubProtocolWebSocketHandlerInterceptor.java
Labels: 🐞bug, 🔨fix

#167 [FIX] 닉네임 수정시 정규식 적용 (#166)
  src/main/java/com/project/trysketch/controller/ImageController.java
  src/main/java/com/project/trysketch/controller/MypageController.java
  src/main/java/com/project/trysketch/dto/request/UserRequestDto.java
  src/main/java/com/project/trysketch/service/ImageService.java
  src/main/java/com/project/trysketch/service/MypageService.java
Labels: 🐞bug

#169 [FIX] 자동 제출 시 게임이 진행되지 않는 에러 (#163)
  src/main/java/com/project/trysketch/controller/GameController.java
  src/main/java/com/project/trysketch/service/GameService.java
Labels: 🐞bug, 🔨fix

#171 [FEAT] 3종 업적 관련기능 추가 (#170)
  src/main/java/com/project/trysketch/controller/MypageController.java
  src/main/java/com/project/trysketch/entity/GameFlow.java
  src/main/java/com/project/trysketch/entity/GameRoomUser.java
  src/main/java/com/project/trysketch/service/GameRoomService.java
  src/main/java/com/project/trysketch/service/GameService.java
  src/main/java/com/project/trysketch/service/HistoryService.java
  src/main/java/com/project/trysketch/service/MypageService.java
Labels: ✨feature

#172 [FEAT] 마이페이지에서 달성된 업적 조회기능 추가 (#170)
  src/main/java/com/project/trysketch/controller/MypageController.java
  src/main/java/com/project/trysketch/controller/UserController.java
  src/main/java/com/project/trysketch/dto/response/AchievementResponseDto.java
  src/main/java/com/project/trysketch/entity/Achievement.java
  src/main/java/com/project/trysketch/entity/GameRoomUser.java
  src/main/java/com/project/trysketch/global/utill/AchievementCode.java
  src/main/java/com/project/trysketch/service/HistoryService.java
  src/main/java/com/project/trysketch/service/MypageService.java
Labels: ✨feature
