Repository Trys-Ketch/trys-ketch-server, pull requests merged in 2023-02, with the labels that each got.

#174 [FEAT] 로그인 업적 달성시 메세지와 함께 달성한 업적이름 반환 (#170)
  src/main/java/com/project/trysketch/controller/UserController.java
  src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
  src/main/java/com/project/trysketch/service/GoogleService.java
  src/main/java/com/project/trysketch/service/HistoryService.java
  src/main/java/com/project/trysketch/service/KakaoService.java
  src/main/java/com/project/trysketch/service/NaverService.java
Labels: ✨feature

#176 로그인 업적 생성안되는 버그 수정
  src/main/java/com/project/trysketch/controller/MypageController.java
  src/main/java/com/project/trysketch/global/utill/AchievementCode.java
  src/main/java/com/project/trysketch/service/GameService.java
  src/main/java/com/project/trysketch/service/GoogleService.java
  src/main/java/com/project/trysketch/service/HistoryService.java
  src/main/java/com/project/trysketch/service/ImageService.java
  src/main/java/com/project/trysketch/service/KakaoService.java
  src/main/java/com/project/trysketch/service/MypageService.java
  src/main/java/com/project/trysketch/service/NaverService.java
Labels: 🔨fix

#178 [REFECTOR] GameService 코드 리팩토링, 자동제출 기능추가
  src/main/java/com/project/trysketch/controller/GameController.java
  src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
  src/main/java/com/project/trysketch/service/GameRoomService.java
  src/main/java/com/project/trysketch/service/GameService.java
Labels: ✨feature, 🔨fix, ♻refactor

#180 업적관련 기능 추가 및 변경
  src/main/java/com/project/trysketch/service/GameService.java
  src/main/java/com/project/trysketch/service/GoogleService.java
  src/main/java/com/project/trysketch/service/HistoryService.java
  src/main/java/com/project/trysketch/service/KakaoService.java
  src/main/java/com/project/trysketch/service/NaverService.java
Labels: ✨feature, 🔨fix, ♻refactor

#181 [FEAT] SSE 적용시 발생하던 오류 해결 및 인원수까지 반영되도록 수정(#68)
  src/main/java/com/project/trysketch/controller/GameController.java
  src/main/java/com/project/trysketch/entity/GameRoom.java
  src/main/java/com/project/trysketch/entity/Image.java
  src/main/java/com/project/trysketch/global/utill/sse/SseController.java
  src/main/java/com/project/trysketch/global/utill/sse/SseEmitters.java
  src/main/java/com/project/trysketch/service/GameRoomService.java
  src/main/java/com/project/trysketch/service/GameService.java
Labels: ✨feature, 🔨fix

#183 [REFACTOR] OAuth2.0 카카오 로그인관련 - REST API키 숨김처리 (#182)
  src/main/java/com/project/trysketch/service/KakaoService.java
Labels: ♻refactor

#184 [FIX] 자동 제출 로직 변경 (#163)
  src/main/java/com/project/trysketch/controller/GameController.java
  src/main/java/com/project/trysketch/entity/GameFlowCount.java
  src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
  src/main/java/com/project/trysketch/repository/GameFlowCountRepository.java
  src/main/java/com/project/trysketch/repository/GameFlowRepository.java
  src/main/java/com/project/trysketch/service/AmazonS3Service.java
  src/main/java/com/project/trysketch/service/GameService.java
  src/main/java/com/project/trysketch/service/ImageService.java
Labels: 🐞bug, 🔨fix

#186 [FIX] 자잘한 코드 수정 (#185)
  src/main/java/com/project/trysketch/controller/GameController.java
  src/main/java/com/project/trysketch/global/config/WebSecurityConfig.java
  src/main/java/com/project/trysketch/service/AmazonS3Service.java
  src/main/java/com/project/trysketch/service/GameService.java
Labels: 🔨fix

#188 [REFACTOR] 주석 추가
  src/main/java/com/project/trysketch/entity/Achievement.java
  src/main/java/com/project/trysketch/entity/Adjective.java
  src/main/java/com/project/trysketch/entity/ChatMessage.java
  src/main/java/com/project/trysketch/entity/GameFlow.java
  src/main/java/com/project/trysketch/entity/GameFlowCount.java
  src/main/java/com/project/trysketch/entity/GameRoomUser.java
  src/main/java/com/project/trysketch/entity/Guest.java
  src/main/java/com/project/trysketch/entity/History.java
  src/main/java/com/project/trysketch/entity/Image.java
  src/main/java/com/project/trysketch/entity/ImageLike.java
  src/main/java/com/project/trysketch/entity/Noun.java
  src/main/java/com/project/trysketch/entity/RandomNick.java
  src/main/java/com/project/trysketch/entity/UnsubmissionImg.java
  src/main/java/com/project/trysketch/entity/UserPlayTime.java
  src/main/java/com/project/trysketch/service/GuestService.java
Labels: ♻refactor

#191 [FEAT] 로그인 시 RefreshToken 적용 (#190)
  src/main/java/com/project/trysketch/controller/UserController.java
  src/main/java/com/project/trysketch/global/config/RedisConfig.java
  src/main/java/com/project/trysketch/global/exception/StatusMsgCode.java
  src/main/java/com/project/trysketch/global/jwt/JwtUtil.java
  src/main/java/com/project/trysketch/global/jwt/RefreshToken.java
  src/main/java/com/project/trysketch/repository/RefreshTokenRepository.java
  src/main/java/com/project/trysketch/service/GuestService.java
  src/main/java/com/project/trysketch/service/SocialLoginService.java
  src/main/java/com/project/trysketch/service/UserService.java
Labels: ✨feature

#195 [Refector] data 필드 타입 수정
  src/main/java/com/project/trysketch/dto/response/DataMsgResponseDto.java
Labels: 🔨fix, ♻refactor
